//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.0.5
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HRPData.Context
{
   /// <inheritdoc/>
   public partial class HRPModel : Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext<HRPData.Entity.HRPUser>
   {
      #region DbSets
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::HRPData.Entity.BaseProduct> BaseProducts { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::HRPData.Entity.EatableProduct> EatableProducts { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::HRPData.Entity.NonEatableProduct> NonEatableProducts { get; set; }

      #endregion DbSets

      /// <inheritdoc />
      public HRPModel(DbContextOptions<HRPModel> options) : base(options)
      {
      }

      partial void CustomInit(DbContextOptionsBuilder optionsBuilder);

      /// <inheritdoc />
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         CustomInit(optionsBuilder);
      }

      partial void OnModelCreatingImpl(ModelBuilder modelBuilder);
      partial void OnModelCreatedImpl(ModelBuilder modelBuilder);

      /// <inheritdoc />
      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         OnModelCreatingImpl(modelBuilder);

         modelBuilder.HasDefaultSchema("dbo");

         modelBuilder.Entity<global::HRPData.Entity.BaseProduct>()
                     .ToTable("BaseProduct")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::HRPData.Entity.BaseProduct>()
                     .Property(t => t.Id)
                     .IsRequired()
                     .ValueGeneratedOnAdd();



         OnModelCreatedImpl(modelBuilder);
      }
   }
}
