# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Server:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v1
    - name: Server
      run: |
        nuget restore
        cd HRPServer
        msbuild HRPServer.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    - uses: actions/upload-artifact@master
      with:
        name: HRPServer
        path: HRPServer/bin/Release/netcoreapp3.1/
  ServerLinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - uses: actions/checkout@v1
    - name: dotnetTools
      run: |
        dotnet tool install --global dotnet-deb
        dotnet deb install
    - name: Server
      run: |
        nuget restore
        cd HRPServer
        dotnet restore 
        dotnet msbuild HRPServer.csproj /verbosity:normal /p:TargetFramework=netcoreapp3.1 /t:Rebuild  /t:CreateDeb /p:RuntimeIdentifier=ubuntu.16.04-x64 /p:Configuration=Release
    - uses: actions/upload-artifact@master
      with:
        name: HRPServer
        path: HRPServer\bin\Debug\netcoreapp3.1\hrpserver.1.0.0.deb
  UWP:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v1
    - name: UWP
      run: |
        nuget restore
        msbuild HRP/HRP.UWP/HRP.UWP.csproj /p:AppxBundlePlatforms="x64|x86" /p:AppxPackageDir="AppPackage" /p:Configuration=Release /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:PackageCertificateKeyFile=HRP.UWP_TemporaryKey.pfx /p:PackageCertificatePassword=${{secrets.Pfx_Key}}
    - uses: actions/upload-artifact@master
      with:
        name: HRP.UWP
        path:  HRP/HRP.UWP/AppPackage/HRP.UWP_1.0.0.0_Test

        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        msbuild HRP/HRP.Android/HRP.Android.csproj /p:AndroidBuildApplicationPackage=True /verbosity:normal /t:Rebuild /p:Configuration=Release
    - uses: actions/upload-artifact@master
      with:
        name: HRP.APK
        path:  HRP/HRP.Android/bin/Release/
        
        
