# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Server:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Server
      run: |
        cd HRPServer
        nuget restore
        msbuild HRPServer.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
  UWP:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: UWP
      run: |
        cd HRP
        nuget restore
        cd HRP.UWP
        msbuild HRP.UWP.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd HRP
        nuget restore
        cd HRP.Android
        msbuild HRP.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd HRP
        nuget restore
        msbuild HRP.iOS/HRP.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
