# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Server:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v1
    - name: Server
      run: |
        nuget restore
        cd HRPServer
        msbuild HRPServer.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    - uses: actions/upload-artifact@master
      with:
        name: HRPServer
        path: HRPServer/bin/Release/netcoreapp3.1/
  UWP:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v1
    - name: UWP
      run: |
        nuget restore
        msbuild HRP/HRP.UWP/HRP.UWP.csproj /p:AppxBundlePlatforms="x64" /p:AppxPackageDir="HRP/HRP.UWP/bin/x64" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload
        cd bin\x86
    - uses: actions/upload-artifact@master
      with:
        name: HRP
        path:  HRP/HRP.UWP/bin/x64
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd HRP/HRP.Android
        msbuild HRP.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    - uses: actions/upload-artifact@master
      with:
        name: APK-sig
        path:  HRP/HRP.Android/bin/Release/com.companyname.hrp-Signed.apk
    - uses: actions/upload-artifact@master
      with:
        name: APK
        path:  HRP/HRP.Android/bin/Release/com.companyname.hrp.apk
        
        
